test_suites:
    - name: lint
      script_path: /root/okta/okta-react-native/scripts
      sort_order: '1'
      timeout: '60'
      script_name: lint
      criteria: MERGE
      queue_name: small
    - name: unit
      script_path: /root/okta/okta-react-native/scripts
      sort_order: '2'
      timeout: '10'
      script_name: unit
      criteria: MERGE
      queue_name: small
    - name: publish
      script_path: /root/okta/okta-react-native/scripts
      sort_order: '3'
      timeout: '60'
      script_name: publish
      criteria: MERGE
      queue_name: small