version: 2.1

orbs:
  general-platform-helpers: okta/general-platform-helpers@1.8

executors:
  apple-ci-arm-medium:
    macos:
      xcode: 14.3.1
    resource_class: macos.m1.medium.gen1

jobs:
  setup:
    executor: apple-ci-arm-medium
    steps:
      - checkout
      - run: gem install cocoapods
      - run: (cd ios; pod install)
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  snyk-scan:
    executor: apple-ci-arm-medium
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Install rosetta # Needed for snyk to work on M1 machines.
          command: softwareupdate --install-rosetta --agree-to-license
      - general-platform-helpers/step-load-dependencies
      - general-platform-helpers/step-run-snyk-monitor:
          run-on-non-main: true
          scan-all-projects: true
          skip-unresolved: false
          os: macos

workflows:
  security-scan:
    jobs:
      - setup:
          #filters:
          #  branches:
          #    only:
          #      - master
      - general-platform-helpers/job-snyk-prepare:
          name: prepare-snyk
          #filters:
          #  branches:
          #    only:
          #      - master
          requires:
            - setup
      - snyk-scan:
          name: execute-snyk
          #filters:
          #  branches:
          #    only:
          #      - master
          requires:
            - prepare-snyk
