require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '12.4'
inhibit_all_warnings!

def shared_pods
  config = use_native_modules!
  use_react_native!(:path => config[:reactNativePath])

  use_native_modules!

  pod 'OktaOidc'
end

target 'ReactNativeOktaSdkBridge' do
  shared_pods
end

target 'Tests' do
  shared_pods
end
