platform :ios, '12.0'
inhibit_all_warnings!

require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'

target 'ReactNativeOktaSdkBridge' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  use_native_modules!

  pod 'OktaOidc'
end

target 'Tests' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  use_native_modules!

  pod 'OktaOidc'
end