name: 'Setup node and run yarn'
description: 'Checkout and run yarn install'
author: 'okta'

inputs:
  node-version:
    description: 'Node version'
    required: true
    default: 16

runs:
  using: "composite"
  steps:
  - name: Checkout
    uses: actions/setup-node@v2
    with:
      node-version: ${{ inputs.node-version }}
  - run: npm install -g yarn 
  - run: yarn install --frozen-lockfile