name: Okta OIDC iOS

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  JSTests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - run: npm install -g yarn 
    - run: sudo apt-get install -y libappindicator1
    - name: Lint
      run: yarn lint
    - name: Test
      run: yarn test
    - name: Execute snyk.sh
      run: bash ./scripts/snyk.sh
      