name: Okta React Native

on:
  push:
    branches: [ master ]
  pull_request:


jobs:
    JSUnitTests:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Configure React Native dependencies (node_modules)
        uses: ./.github/workflows/composite/configure-node
        with:
          node-path: ./node_modules
          lock-hash: ${{ hashFiles('yarn.lock') }}
      - run: sudo apt-get install -y libappindicator1
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
      - name: Execute snyk.sh
        run: bash ./scripts/snyk.sh
    iOSUnitTests:
      runs-on: macos-11
      steps:
      - uses: actions/checkout@v2
      - name: Configure React Native dependencies (node_modules)
        uses: ./.github/workflows/composite/configure-node
        with:
          node-path: ./node_modules
          lock-hash: ${{ hashFiles('yarn.lock') }}
      - name: Cache CocoaPods
        id: pods-cache
        uses: actions/cache@v2
        with:
          path: ./ios/Pods
          key: pods-${{ hashFiles('./ios/Podfile.lock') }}          
      - name: Preparation before iOS Build
        run: |
          pod install --project-directory=ios --repo-update
      - name: iOS
        run: | 
          set -o pipefail
          xcodebuild \
          -workspace ios/ReactNativeOktaSdkBridge.xcworkspace \
          -scheme "ReactNativeOktaSdkBridge" \
          -destination "platform=iOS Simulator,OS=latest,name=iPhone 12" \
          clean test | xcpretty
    iOSUITests:
      runs-on: macos-11
      steps:
      - uses: actions/checkout@v2
      - name: Cache ./node_modules    
        uses: ./.github/workflows/composite/configure-node
        with:  
          node-path: ./node_modules
          lock-hash: ${{ hashFiles('yarn.lock') }}
      - name: Build okta-react-native package
        run: yarn build 
      - name: Cache e2e/node_modules
        uses: ./.github/workflows/composite/configure-node
        with:  
          node-path: ./e2e/node_modules
          lock-hash: ${{ hashFiles('./e2e/yarn.lock') }}
          install-path: ./e2e
      - name: Cache CocoaPods
        id: pods-cache
        uses: actions/cache@v2
        with:
          path: ./e2e/ios/Pods
          key: pods-${{ hashFiles('./e2e/ios/Podfile.lock') }}
      - name: Preparation before iOS Build
        run: |
          npm install -g react-native-cli
          cd e2e
          yarn bundle:ios
          cd ios
          pod install --repo-update
          cd ../..
          echo -e "CLIENT_ID=${{ secrets.CLIENT_ID }}\nISSUER=${{ secrets.ISSUER }}\nREDIRECT_URI=${{ secrets.REDIRECT_URI }}\nLOGOUT_REDIRECT_URI=${{secrets.LOGOUT_REDIRECT_URI}}" > e2e/.env
      - name: iOS
        env: 
          OKTA_USERNAME: ${{ secrets.OKTA_USERNAME }}
          OKTA_PASSWORD: ${{ secrets.OKTA_PASSWORD }}
        run: | 
          set -o pipefail 
          xcodebuild \
          -workspace e2e/ios/E2EOktaReactNative.xcworkspace \
          -scheme E2EOktaReactNative \
          -destination 'platform=iOS Simulator,OS=latest,name=iPhone 12' \
          -configuration CI \
          -sdk iphonesimulator \
          clean test | xcpretty